### ISSUE TITLE
Hello, I tried your code but despite the different real .pdbs I used as input, I got the following error: 

### ISSUE THREAD

**Issue by Fede1612** [llrs/PYT-SBI#3]
`/blast.py, line 74, in analyze_blast_result
value[2]: value[3]}
IndexError: list index out of range`

**Comment by Fede1612** [comment]
Hello, i tried your code, but despite pdbs used as input..I got the following error.

**Comment by llrs** [comment]
Hi thanks for using this program.
In order to find the source of the problem and fix it I would need some more information. Which PDB codes were you using? And what is the exact command you used?

**Comment by Fede1612** [comment]
> Hi thanks for using this program.
> In order to find the source of the problem and fix it I would need some more information. Which PDB codes were you using? And what is the exact command you used?

Hello, I think I made some mistakes in installing it. is there a requirement.txt that specify the modules that are needed?

**Comment by llrs** [comment]
No, there isn't any requirements.txt. We never thought it would be much used, but I might get into it see #4. Anyway, if you want to report your experiences it will be helpful to know what can be improved.

**Comment by llrs** [comment]
I have just added a requirements.txt. Let me know if you could install it or if it works for you now. 
Sorry, haven't touched python in a while, if it doesn't work see the packaging branch or #4 (any help on that direction is welcomed).
